version: '3.8'
services:
  localstack:
    container_name: localstack
    image: localstack/localstack-pro
    ports:
      - "4566:4566"            # LocalStack Gateway
      - "4510-4559:4510-4559"  # external services port range
    environment:
      - DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=ecs,ec2,iam,route53,events
      - LOCALSTACK_AUTH_TOKEN=${LOCALSTACK_AUTH_TOKEN:?}
    volumes:
      - "${LOCALSTACK_VOLUME_DIR:-./volume}:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"

  react-app:
    build:
      context: ./website
      dockerfile: Dockerfile
    image: react-hello-world:latest
